#!/bin/bash

mvn clean compile

# get classpath of dependencies and store in a variable
mvn dependency:build-classpath -Dmdep.outputFile=cp.txt
cp=$(<cp.txt)
rm cp.txt

# run tests
echo "java processing server waiting for calls..."
java -cp $cp:target/classes ncsusoftware.Main


# ## demo on how to call code for "hole injection"
# java -cp $cp:target/classes ncsusoftware.HoleInjectionMain "Assert.assertEquals(OBJECT, byteSerializer.deserializeNative(buffer));" > out.txt
# echo "---"
# cat out.txt
# echo "---"
# rm out.txt
